export const ADD_PLAYER = "ADD_PLAYER";
export const REMOVE_PLAYER = "REMOVE_PLAYER";
export const SET_PLAYERS = "SET_PLAYERS";
export const FETCH_PLAYERS_FAILED = "FETCH_PLAYERS_FAILED";

export const SAVE_TEAM_SUCCESS = "SAVE_TEAM_SUCCESS";
export const SAVE_TEAM_FAIL = "SAVE_TEAM_FAIL";
export const SAVE_TEAM_START = "SAVE_TEAM_START";
export const SAVE_INIT = "SAVE_INIT";

export const FETCH_SAVES_START = "FETCH_SAVES_START";
export const FETCH_SAVES_SUCCESS = "FETCH_SAVES_SUCCESS";
export const FETCH_SAVES_FAIL = "FETCH_SAVES_FAIL";
